title: 'Clinical trial results extraction with LLMs'
description: "Using an LLM in a spaCy pipeline to extract patient groups, treatments and outcomes in clinical trials."

vars:
  ner_config: "ner_openai.cfg"
  trial_config: "trial_openai.cfg"
  pmid: 27144689

# These are the directories that the project needs.
directories: ["assets", "configs", "scripts"]

# Assets that should be available in the directory.
assets:
  - dest: "assets/23206895.txt"
  - dest: "assets/27144689.txt"
  - dest: "assets/35172054.txt"

# Project commands
commands:
  - name: zero_shot_ner
    help: "Run an LLM pipeline with zero-shot NER"
    script:
      - "python ./scripts/visualise_entities.py ${vars.pmid} ./configs/${vars.ner_config}"
    deps:
      - "assets/${vars.pmid}.txt"
      - "configs/${vars.ner_config}"

  - name: summarize
    help: "Run the LLM-powered spaCy pipeline"
    script:
      - "python ./scripts/extract_results.py ${vars.pmid} ./configs/${vars.trial_config}"
    deps:
      - "assets/${vars.pmid}.txt"
      - "configs/${vars.trial_config}"
